### PR TITLE
Add rebar3 versions 3.4.2 through 3.4.7

### PR DESCRIPTION
**Pull request by sanmiguel**

### CODE REVIEW

**Comment by Stratus3D** [comment]
Awesome! Thanks so much!

**Comment by sanmiguel** [comment]
You're welcome! Thanks for merging so quick :) 👍

**Comment by Stratus3D** [comment]
@sanmiguel since your using this plugin, let me know if you come across any errors during the installation of rebar3. The build has been failing for quite a while (it's got nothing to do with your changes) and I haven't figured out why.

#2

**Comment by sanmiguel** [comment]
Will do, thanks! No errors so far, but I've only been using it since this morning :)

**Pull request merged**
